### ISSUE TITLE
[RLStats] TODO List

### ISSUE THREAD

**Issue by Jackenmen** [jack1142/JackCogs#1]
# TODO
### Core functionality
- [x] customize background image - set own bg image and its overlay percentage (separately for `[p]rlstats` and `[p]rlsports`)
- [x] add ranked sports
- [x] `[p]rlstats` is too complex
### API functionality
- [x] use rocketleague.tracker.network for tier breakdown (servers are more stable, breakdown will contain extra modes)
#### UI:
  - [x] add icons (and maybe indication in message's content) for platforms (possibly indicate that profile connection was used)
  - [x] add number of wins (there's no text right now, only bars)
#### Code quality:
  - [x] put drawing into separate file?
  - [ ] try to lower the amount of code for tier and division estimates

**Comment by Jackenmen** [comment]
All this stuff is done.
