### ISSUE TITLE
[unfinished-cogs/] Prepare stuff for pending branch removal for cogs merged into `v3`

### ISSUE THREAD

**Issue by Jackenmen** [jack1142/JackCogs#8]
- [x] Determine date of branch removal
- [x] Send message to owners about branch removal
- [x] DM known users

Affected cogs:
- [x] banmessage
- [x] modroles
- [x] nitrorole

**Comment by Jackenmen** [comment]
Closing this, there's one possible user of my cogs who isn't in Red servers anymore so unless he accepts my friend request, I can't DM him.
Edited: DMed that user
